full_rebuild: true
name: Wakanda Studio
author: Wakanda SAS
url: http://wakanda.io
version: 0.1
repository: https://github.com/Wakanda/wakanda-studio
branch: gh-pages
encoding: utf-8
theme: wakanda
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
